#!/usr/bin/env bash
# This script will displays numbers from 1 to 100.
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number


for (( x=1; x < 101; x++ ))
do
    if (( x % 15 == 0 )); then
	echo "FizzBuzz"
    elif (( x % 3 == 0 )); then
	echo "Fizz"
    elif (( x % 5 == 0 )); then
	echo "Buzz"
    else
	echo "$x"
    fi
done


			 
