#!/usr/bin/env bash
# Now that you’ve parsed the Apache log file, let’s sort the data so you can get a better idea of what is going on.
# Using what you did in the previous exercise, write a Bash script that groups visitors by IP and HTTP status code, and displays this data.

x="apache-access.log"
awk '{print $1, $9}' $x | sort | uniq -c | sort -nr
