#!/usr/bin/env bash
# This script will display the time for 12hours and 59minutes.

h=0
while [ "$h" -le 12 ]
do echo "Hour: $h"
   (( h++ ))
   x=1
   while [ "$x" -le 59 ]
	 do echo "$x"
	    (( x++ ))
   done
done




