#!/usr/bin/env bash
# This script will display the content of the current directory in a list format
# Using for, and without displaying hidden files

export x=kirikou
for x in *;
do find . -type d -path '*/.*' -prune -o -not -name '.*' -type f | cut -d "-" -f2
done
