#!/usr/bin/env bash
# This script will display the content of the current directory in a list format
# Using for, and without displaying hidden files

x="$(ls)"
for x in $x;
do
    echo "$x" | cut -d "-" -f2

done
