#!/usr/bin/env bash
# This script will give information about "school" file. Using if and else.
# The script will check if the file exists and print it.

x="school"

if [ -e "$x" ]
then echo "$x file exists"
     if [ -s "$x" ]
     then echo "$x is not empty"
     else echo "$x file is empty"
     fi

     if [ -f "$x" ]
     then echo "$x is a regular file"
     fi
else echo "$x file does not exist"
fi
