#!/usr/bin/env bash
# This script will give information about "school" file. Using if and else.
# The script will check if the file exists and print it.

x="school"

if [ -e $x ]
then  echo "$x file exists"

if [ ! -e $x ]
then echo "$x file does not exist"

if [ ! -s $x ]
then echo "$x file is empty"

if [ -s $x ]
then echo "$x file is not empty"

if [ -f $x ]
then echo "$x is a regular file"

else [ ! -f $x ] :
fi
fi
fi
fi
fi

