#!/usr/bin/env bash
# Write a Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

x=1


trap "echo I hate the kill command ; rm -r /var/run/myscript.pid" SIGTERM
trap "echo  Y U no love me?!" SIGINT
trap "rm -r /var/run/myscript.pid ; exit" SIGTERM SIGQUIT

while [ $x -eq 1 ]
do echo "To infinity and beyond"
   echo " ps -aux  "> /var/run/myscript.pid

done


