#!/usr/bin/env bash
# Write a Bash script that:
# Indefinitely writes I am alive! to the file /tmp/my_process
# In between every I am alive! message, the program should pause for 2 seconds
# Write Bash (init) script 11-manage_my_process that manages manage_my_process. (both files need to be pushed to git)


argv1=$1

tmpfile="/var/run/my_process.pid"

startLoop_n_createFile()
{
./manage_my_process &
 echo "$!" > "$tmpfile"
}

 killLoop_n_rmFile()
 {
 
 sudo pkill -f "./manage_my_process"
 rm "$tmpfile"
 }
 
 case "$argv1" in
     start) echo "manage_my_process started"
 startLoop_n_createFile
 ;;
     stop) echo "manage_my_process stopped"
 killLoop_n_rmFile
 ;;
     restart) echo "manage_my_process restarted"
 killLoop_n_rmFile
 startLoop_n_createFile
 ;;
 *) echo "Usage: manage_my_process {start|stop|restart}"
 ;;
	esac

